name: spedread
base: core22
adopt-info: spedread
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

slots:
  spedread:
    interface: dbus
    bus: session
    name: com.github.Darazaki.Spedread

apps:
  spedread:
    command: usr/bin/spedread
    extensions: [gnome]
    common-id: com.github.Darazaki.Spedread
    desktop: usr/share/applications/com.github.Darazaki.Spedread.desktop


parts:
  spedread:
    source: https://github.com/Darazaki/Spedread.git
    plugin: meson
    parse-info: [usr/share/appdata/com.github.Darazaki.Spedread.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
      - -Dadw_1_2=true
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      sed -e 's|Icon=com.github.Darazaki.Spedread|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.Darazaki.Spedread.svg|' -i data/com.github.Darazaki.Spedread.desktop.in
    
